#!/bin/bash

echo "======================================"
echo "  GitHub 上传指南"
echo "======================================"
echo ""
echo "步骤 1: 在 GitHub 创建新仓库"
echo "  - 访问: https://github.com/new"
echo "  - 仓库名: MiuixFloatingNavDemo"
echo "  - 设为公开 (Public)"
echo "  - 不要添加 README、.gitignore 或 license"
echo ""
echo "步骤 2: 在此目录执行以下命令"
echo ""
echo "  git init"
echo "  git add ."
echo "  git commit -m 'Initial commit: Miuix FloatingNavigationBar demo'"
echo "  git branch -M main"
echo "  git remote add origin https://github.com/你的用户名/MiuixFloatingNavDemo.git"
echo "  git push -u origin main"
echo ""
echo "步骤 3: 等待 GitHub Actions 自动构建"
echo "  - 访问仓库的 Actions 标签页"
echo "  - 等待构建完成（约 3-5 分钟）"
echo "  - 下载构建产物中的 APK"
echo ""
echo "======================================"
